import Link from "next/link";

export const metadata = {
  title: "Terms & Conditions — ReportGenius",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <nav className="mb-8 text-sm text-gray-500">
          <Link href="/login" className="hover:text-gray-900">← Back to login</Link>
        </nav>

        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms & Conditions</h1>
        <p className="text-sm text-gray-500 mb-8">Last updated: March 2026</p>

        <div className="prose prose-gray max-w-none space-y-8">

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">Acceptance</h2>
            <p className="text-gray-700">
              By creating an account you agree to these Terms & Conditions and our Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">Use of Service</h2>
            <ul className="list-disc pl-5 space-y-2 text-gray-700">
              <li>ReportGenius is provided free of charge for educational use</li>
              <li>You must be a qualified teacher or authorised school staff member</li>
              <li>You are responsible for the accuracy of data you enter</li>
              <li>You must have your school&apos;s permission to use third-party tools for storing student data</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">Your Responsibilities as Data Controller</h2>
            <p className="text-gray-700 mb-3">
              Under UK GDPR, you (the teacher/school) are the data controller for any student data you enter.
              You are responsible for:
            </p>
            <ul className="list-disc pl-5 space-y-2 text-gray-700">
              <li>Ensuring you have a lawful basis to process student data</li>
              <li>Informing your school&apos;s Data Protection Officer if required</li>
              <li>Not entering more student data than necessary for the purpose</li>
              <li>Deleting data when it is no longer needed</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">Acceptable Use</h2>
            <p className="text-gray-700 mb-3">You must not:</p>
            <ul className="list-disc pl-5 space-y-2 text-gray-700">
              <li>Enter data for students without authorisation</li>
              <li>Share your account credentials with others</li>
              <li>Attempt to access other users&apos; data</li>
              <li>Use the service for any purpose other than generating school reports</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">Open Source</h2>
            <p className="text-gray-700">
              This software is open source. The source code is available on GitHub under the MIT licence.
              Self-hosted deployments are the responsibility of the host.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">Service Availability</h2>
            <p className="text-gray-700">
              This is a free service with no SLA guarantee. We reserve the right to suspend or discontinue
              the service with reasonable notice where possible.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">Limitation of Liability</h2>
            <p className="text-gray-700">
              The service is provided &quot;as is&quot;. We accept no liability for data loss, service interruption,
              or report content generated by AI models. Teachers are responsible for reviewing and editing
              all AI-generated content before it is used.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">Changes to Terms</h2>
            <p className="text-gray-700">
              We may update these terms. Continued use of the service after changes constitutes acceptance
              of the updated terms.
            </p>
          </section>

        </div>

        <footer className="mt-12 pt-8 border-t border-gray-200 flex gap-4 text-sm text-gray-500">
          <Link href="/privacy-policy" className="hover:text-gray-900">Privacy Policy</Link>
          <Link href="/terms" className="hover:text-gray-900">Terms & Conditions</Link>
        </footer>
      </div>
    </div>
  );
}
