/**
 * Students routes
 *
 * POST   /api/v1/classes/:classId/students        — create single student
 * POST   /api/v1/classes/:classId/students/bulk   — bulk create (max 100)
 * GET    /api/v1/classes/:classId/students        — list students
 * DELETE /api/v1/students/:studentId              — delete if no final reports exist
 *
 * Multi-tenant isolation: every operation first verifies classId belongs to
 * req.user.organizationId before touching any data.
 *
 * Privacy: last_name and student_ref_id are stored locally.
 * They are NEVER included in LLM prompts. anonymous_token is auto-generated.
 */

import { Router, Request, Response, NextFunction } from "express";
import { z } from "zod";
import { PrismaClient } from "@prisma/client";
import { randomUUID } from "crypto";
import { authenticate } from "../middleware/auth";

const router = Router();
const prisma = new PrismaClient();

// ── Zod schemas ──────────────────────────────────────────────────────────────

const CreateStudentSchema = z.object({
  first_name: z.string().min(1, "first_name is required").max(100),
  last_name: z.string().max(100).optional(),
  student_ref_id: z.string().max(100).optional(),
  gender: z.string().max(20).optional(),
  internal_notes: z.string().optional(),
});

const BulkCreateStudentsSchema = z.object({
  students: z
    .array(
      z.object({
        first_name: z.string().min(1, "first_name must be at least 1 character").max(100),
        last_name: z.string().min(1, "last_name must be at least 1 character").max(100),
        student_ref_id: z.string().max(100).nullable().optional(),
        gender: z.string().nullable().optional().transform((val) => {
          if (!val) return null;
          const upper = val.trim().toUpperCase();
          if (upper === "M") return "M";
          if (upper === "F") return "F";
          if (upper === "OTHER") return "Other";
          return null;
        }),
        internal_notes: z.string().optional(),
      })
    )
    .min(1, "students array must not be empty")
    .max(100, "Cannot import more than 100 students at once"),
});

// ── Helper: verify class belongs to org ─────────────────────────────────────

async function resolveClass(
  classId: string,
  organizationId: string
): Promise<{ id: string; organization_id: string } | null> {
  return prisma.class.findFirst({
    where: { id: classId, organization_id: organizationId },
    select: { id: true, organization_id: true },
  });
}

// ── POST /api/v1/classes/:classId/students ───────────────────────────────────

router.post(
  "/classes/:classId/students",
  authenticate,
  async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const classId = String(req.params["classId"]);
      const organizationId = req.user.organizationId;

      const cls = await resolveClass(classId, organizationId);
      if (!cls) {
        res.status(404).json({ error: "Class not found", code: "CLASS_NOT_FOUND" });
        return;
      }

      const parsed = CreateStudentSchema.safeParse(req.body);
      if (!parsed.success) {
        res.status(400).json({
          error: parsed.error.errors.map((e) => e.message).join(", "),
          code: "VALIDATION_ERROR",
        });
        return;
      }

      const { first_name, last_name, student_ref_id, gender, internal_notes } = parsed.data;

      const student = await prisma.student.create({
        data: {
          organization_id: organizationId,
          class_id: classId,
          first_name,
          last_name: last_name ?? null,
          student_ref_id: student_ref_id ?? null,
          gender: gender ?? null,
          internal_notes: internal_notes ?? null,
          // anonymous_token auto-generated by Prisma default(uuid())
        },
        select: {
          id: true,
          first_name: true,
          last_name: true,
          student_ref_id: true,
          gender: true,
          internal_notes: true,
          anonymous_token: true,
          created_at: true,
        },
      });

      console.log(JSON.stringify({
        event: "student.created",
        studentId: student.id,
        classId,
        organizationId,
      }));

      res.status(201).json({ student });
    } catch (err) {
      next(err);
    }
  }
);

// ── POST /api/v1/classes/:classId/students/bulk ──────────────────────────────

router.post(
  "/classes/:classId/students/bulk",
  authenticate,
  async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const classId = String(req.params["classId"]);
      const organizationId = req.user.organizationId;

      const cls = await resolveClass(classId, organizationId);
      if (!cls) {
        res.status(404).json({ error: "Class not found", code: "CLASS_NOT_FOUND" });
        return;
      }

      const parsed = BulkCreateStudentsSchema.safeParse(req.body);
      if (!parsed.success) {
        res.status(400).json({
          error: parsed.error.errors.map((e) => e.message).join(", "),
          code: "VALIDATION_ERROR",
        });
        return;
      }

      const { students: studentInputs } = parsed.data;

      const results = { imported: 0, skipped: 0, errors: [] as string[] };
      const createdStudents: {
        id: string;
        first_name: string;
        last_name: string | null;
        student_ref_id: string | null;
        gender: string | null;
        created_at: Date;
      }[] = [];

      for (const s of studentInputs) {
        try {
          const student = await prisma.student.create({
            data: {
              id: randomUUID(),
              organization_id: organizationId,
              class_id: classId,
              first_name: s.first_name,
              last_name: s.last_name ?? null,
              student_ref_id: s.student_ref_id || null,
              gender: s.gender ?? null,
              internal_notes: s.internal_notes ?? null,
            },
            select: {
              id: true,
              first_name: true,
              last_name: true,
              student_ref_id: true,
              gender: true,
              created_at: true,
            },
          });
          createdStudents.push(student);
          results.imported++;
        } catch (err: unknown) {
          results.skipped++;
          const msg = err instanceof Error ? err.message : String(err);
          results.errors.push(`${s.first_name} ${s.last_name}: ${msg}`);
        }
      }

      console.log(JSON.stringify({
        event: "students.bulk_created",
        classId,
        organizationId,
        imported: results.imported,
        skipped: results.skipped,
      }));

      res.status(201).json({
        students: createdStudents,
        imported: results.imported,
        skipped: results.skipped,
        errors: results.errors,
      });
    } catch (err) {
      next(err);
    }
  }
);

// ── GET /api/v1/classes/:classId/students ────────────────────────────────────

router.get(
  "/classes/:classId/students",
  authenticate,
  async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const classId = String(req.params["classId"]);
      const organizationId = req.user.organizationId;

      const cls = await resolveClass(classId, organizationId);
      if (!cls) {
        res.status(404).json({ error: "Class not found", code: "CLASS_NOT_FOUND" });
        return;
      }

      const students = await prisma.student.findMany({
        where: { class_id: classId, organization_id: organizationId },
        select: {
          id: true,
          first_name: true,
          last_name: true,
          student_ref_id: true,
          gender: true,
          internal_notes: true,
          created_at: true,
        },
        orderBy: { first_name: "asc" },
      });

      res.status(200).json({ students, count: students.length });
    } catch (err) {
      next(err);
    }
  }
);

// ── PUT /api/v1/students/:studentId ──────────────────────────────────────────
// Edit first_name, last_name, student_ref_id, gender.

const UpdateStudentSchema = z.object({
  first_name: z.string().min(1, "first_name is required").max(100).optional(),
  last_name: z.string().max(100).nullable().optional(),
  student_ref_id: z.string().max(100).nullable().optional(),
  gender: z.string().max(20).nullable().optional(),
});

router.put(
  "/students/:studentId",
  authenticate,
  async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const studentId = String(req.params["studentId"]);
      const organizationId = req.user.organizationId;

      const student = await prisma.student.findFirst({
        where: { id: studentId, organization_id: organizationId },
        select: { id: true },
      });

      if (!student) {
        res.status(404).json({ error: "Student not found", code: "STUDENT_NOT_FOUND" });
        return;
      }

      const parsed = UpdateStudentSchema.safeParse(req.body);
      if (!parsed.success) {
        res.status(400).json({
          error: parsed.error.errors.map((e) => e.message).join(", "),
          code: "VALIDATION_ERROR",
        });
        return;
      }

      const updateData: Record<string, string | null> = {};
      if (parsed.data.first_name !== undefined) updateData["first_name"] = parsed.data.first_name;
      if (parsed.data.last_name !== undefined) updateData["last_name"] = parsed.data.last_name;
      if (parsed.data.student_ref_id !== undefined) updateData["student_ref_id"] = parsed.data.student_ref_id;
      if (parsed.data.gender !== undefined) updateData["gender"] = parsed.data.gender;

      const updated = await prisma.student.update({
        where: { id: studentId },
        data: updateData,
        select: {
          id: true,
          first_name: true,
          last_name: true,
          student_ref_id: true,
          gender: true,
          created_at: true,
        },
      });

      console.log(JSON.stringify({
        event: "student.updated",
        studentId,
        organizationId,
      }));

      res.status(200).json({ student: updated });
    } catch (err) {
      next(err);
    }
  }
);

// ── DELETE /api/v1/students/:studentId ───────────────────────────────────────
// Only allowed if no final (non-draft) reports exist for this student.

router.delete(
  "/students/:studentId",
  authenticate,
  async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const studentId = String(req.params["studentId"]);
      const organizationId = req.user.organizationId;

      const student = await prisma.student.findFirst({
        where: { id: studentId, organization_id: organizationId },
        select: { id: true },
      });

      if (!student) {
        res.status(404).json({ error: "Student not found", code: "STUDENT_NOT_FOUND" });
        return;
      }

      // Block deletion if any final (non-draft) reports exist for this student.
      const finalReportCount = await prisma.report.count({
        where: {
          student_id: studentId,
          organization_id: organizationId,
          status: { not: "draft" },
        },
      });

      if (finalReportCount > 0) {
        res.status(409).json({
          error: "Cannot delete student with final reports. Archive or delete reports first.",
          code: "STUDENT_HAS_FINAL_REPORTS",
        });
        return;
      }

      await prisma.student.delete({ where: { id: studentId } });

      console.log(JSON.stringify({
        event: "student.deleted",
        studentId,
        organizationId,
      }));

      res.status(204).send();
    } catch (err) {
      next(err);
    }
  }
);

// ── GET /api/v1/students/:studentId/ratings-history ──────────────────────────
// Returns all sessions (most recent first, limit 10) where this student has
// at least one rating, with per-discipline scores.
// Optional query param: ?excludeSessionId=<id>  — omits that session from results.
// Always returns [] for no history; never 404 (student-not-found aside).

router.get(
  "/students/:studentId/ratings-history",
  authenticate,
  async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const studentId = String(req.params["studentId"]);
      const organizationId = req.user.organizationId;
      const excludeSessionId = req.query["excludeSessionId"] as string | undefined;

      // Verify student belongs to this org.
      const student = await prisma.student.findFirst({
        where: { id: studentId, organization_id: organizationId },
        select: { id: true },
      });
      if (!student) {
        res.status(404).json({ error: "Student not found", code: "STUDENT_NOT_FOUND" });
        return;
      }

      // Find sessions (org-scoped) where this student has at least one rating.
      const sessions = await prisma.reportSession.findMany({
        where: {
          organization_id: organizationId,
          ...(excludeSessionId ? { id: { not: excludeSessionId } } : {}),
          disciplines: {
            some: {
              ratings: {
                some: { student_id: studentId },
              },
            },
          },
        },
        select: {
          id: true,
          name: true,
          created_at: true,
          class: { select: { name: true } },
          disciplines: {
            select: {
              name: true,
              ratings: {
                where: { student_id: studentId },
                select: { score: true },
              },
            },
            orderBy: { created_at: "asc" },
          },
        },
        orderBy: { created_at: "desc" },
        take: 10,
      });

      const history = sessions.map((sess) => ({
        sessionId: sess.id,
        sessionName: sess.name,
        className: sess.class.name,
        createdAt: sess.created_at,
        disciplines: sess.disciplines
          .filter((d) => d.ratings.length > 0)
          .map((d) => ({ name: d.name, score: d.ratings[0].score })),
      }));

      res.status(200).json({ history });
    } catch (err) {
      next(err);
    }
  }
);

export default router;
